QuotesWebApp/Models/AllQuotes.cs
namespace QuotesWebApp.Models
{
    public class AllQuotes
    {
        public string AuthorName { get; set; }

        public string Description { get; set; }

        public string Sources { get; set; }
    }
}

QuotesWebApp/Models/AllQuotesViewModel.cs
using AutoMapper;
using Azure;
using System.Reflection.Metadata.Ecma335;

namespace QuotesWebApp.Models
{
    public class AllQuotesViewModel
    {
        public int QuoteId { get; set; }

        public int AuthorId { get; set; }
        public string AuthorName { get; set; }

        public string Description { get; set; }

        public string Sources { get; set; }

        public int CurrentVoteCount { get; set; }

    }
}

QuotesWebApp/Models/CreateQuotesViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace QuotesWebApp.Models
{
    public class CreateQuotesViewModel
    {
        [Required]
        public string Sources { get; set; }

        [Required]
        public string Description { get; set; }


        public int AuthorId { get; set;  }
    }

}

QuotesWebApp/Controllers/QuotesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using QuotesWebApp.Data;
using QuotesWebApp.Models;
using QuotesWebApp.Service;

namespace QuotesWebApp.Controllers
{
    public class QuotesController : Controller
    {
        private ApplicationDbContext _db;
        private QuotesService _quotesService;
        private VoteService _voteService;
        public QuotesController(ApplicationDbContext applicationDb,QuotesService service, VoteService voteService)
        {
            this._db = applicationDb;
            _quotesService = service;
            _voteService = voteService;

        }


        [HttpGet]
        public IActionResult CreateQuotes(int authorId)
        {

            var author = _db.Authors.Where(x => x.Id == authorId).Select(x => new CreateQuotesViewModel()
            {
                AuthorId = authorId
            }).FirstOrDefault();

            int id = _quotesService.GetAuthorIdForQuotes(authorId);

            CreateQuotesViewModel model = new CreateQuotesViewModel()
            {
               AuthorId= id
            };



            return View(model);
        }
        
        public IActionResult CreateQuotes(CreateQuotesViewModel model)
        {
           
            _quotesService.CreateQuotes(model);

            return RedirectToAction("Index","Home");
        }

        [HttpGet]
        public async Task<IActionResult> AllQuotes(int authorId)
        {
          
            var getAllQuotes = await _quotesService.AllQutes(authorId);
         
                      
            return View(getAllQuotes);

        }
    }
}

QuotesWebApp/Views/Quotes/AllQuotes.cshtml
@model List<AllQuotesViewModel>
@{
    ViewData["Tatle"] = "All Person Quotes and sources for them";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></link>
</head>

<h1>
    @ViewData["Title"]
</h1>

<h6></h6>

@foreach (var quotes in Model)
{
    <div class="card">
        <div class="card-header">
            Quote
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>@quotes.Description</p>
                <footer class="blockquote-footer">@quotes.AuthorName<cite title="Source Title:">@quotes.Sources</cite></footer>
            </blockquote>
            <div class="text-muted large ml-3">
                <div>
                    <a href="#" onclick="sendVote(@quotes.QuoteId,true)">
                        <i class="fa fa-thumbs-up"></i>
                    </a>                    
                </div>
                
                <div id="currentCount">@quotes.CurrentVoteCount</div>
               
                <div>
                    <a href="#" onclick="sendVote(@quotes.QuoteId,false)"><i class="fa fa-thumbs-down"></i></a>
                </div>
            </div>
        </div>
    </div>
}


<script>
 
        function sendVote(quoteId,isUpVote,currentCount) {
           
            var json = { quoteId: quoteId, isUpVote:isUpVote};
            console.log(json);
            $.ajax({
                url: "/api/Vote",
                type: "POST",
                data: JSON.stringify(json),
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (data) {                     
                    $("#currentCount").html(data.currentCount);
                }

            });

        }

</script>


    
   

QuotesWebApp/Views/Quotes/CreateQuotes.cshtml
@model CreateQuotesViewModel
@{
    ViewData["Title"] = "Create Author Quotes";
}

<h1>@this.ViewData["Title"]</h1>

<form method="post" asp-action="CreateQuotes" asp-controller="Quotes">
    

    <div class="form-group">
        <label for="Descriptopn">Write quote</label>

        <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" asp-for="Description"></textarea>
    </div>

    <div class="input-group mb-3">

        <span class="input-group-text" id="inputGroup-sizing-default" asp-validation-for="Sources">Sources:</span>
        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" asp-for="Sources">
    </div>


    <div>

        <input asp-action="CreateQuotes" asp-controller="Quotes" asp-route-authorId="@Model.AuthorId" class="btn" type="submit" value="Add the Quote" style="background-color:blueviolet;" >
    </div>


</form>